In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.naive_bayes import GaussianNB
import pickle

In [2]:
with open('census.pkl', 'rb') as f:
    (X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste) = pickle.load(f)

In [3]:
X_census_treinamento.shape, y_census_treinamento.shape

((27676, 108), (27676,))

In [4]:
X_census_teste.shape, Y_census_teste.shape

((4885, 108), (4885,))

In [5]:
naive_census = GaussianNB()
naive_census.fit(X_census_treinamento, y_census_treinamento)
previsoes = naive_census.predict(X_census_teste)
previsoes

array([' >50K', ' >50K', ' >50K', ..., ' <=50K', ' >50K', ' >50K'],
      dtype='<U6')

In [6]:
Y_census_teste

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [8]:
accuracy_score(Y_census_teste, previsoes)

0.4767656090071648

In [9]:
confusion_matrix(Y_census_teste, previsoes)

array([[1172, 2521],
       [  35, 1157]], dtype=int64)

In [10]:
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste = pickle.load(f)

In [11]:
X_census_treinamento.shape, y_census_treinamento.shape

((27676, 108), (27676,))

In [12]:
X_census_teste.shape, Y_census_teste.shape

((4885, 108), (4885,))

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
census_tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
census_tree.fit(X_census_treinamento, y_census_treinamento)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [15]:
previsoes = census_tree.predict(X_census_teste)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [17]:
accuracy_score(Y_census_teste, previsoes)

0.8104401228249745

In [18]:
confusion_matrix(Y_census_teste, previsoes)

array([[3227,  466],
       [ 460,  732]], dtype=int64)

In [19]:
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste = pickle.load(f)

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
random_forest_census = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
random_forest_census.fit(X_census_treinamento,y_census_treinamento)

RandomForestClassifier(criterion='entropy', random_state=0)

In [22]:
previsoes = random_forest_census.predict(X_census_teste)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
accuracy_score(Y_census_teste, previsoes)

0.8507676560900717

In [25]:
confusion_matrix(Y_census_teste, previsoes)

array([[3420,  273],
       [ 456,  736]], dtype=int64)

In [26]:
classification_report(Y_census_teste, previsoes)

'              precision    recall  f1-score   support\n\n       <=50K       0.88      0.93      0.90      3693\n        >50K       0.73      0.62      0.67      1192\n\n    accuracy                           0.85      4885\n   macro avg       0.81      0.77      0.79      4885\nweighted avg       0.85      0.85      0.85      4885\n'

In [27]:
import Orange

In [28]:
base_census = Orange.data.Table('census_regras.csv')

In [29]:
base_census.domain

[age, workclass, final-weight, education, education-num, marital-status, occupation, relationship, race, sex, capital-gain, capital-loos, hour-per-week, native-country | income]

In [30]:
marjority = Orange.classification.MajorityLearner()

In [31]:
previsoes = Orange.evaluation.testing.TestOnTestData(base_census, base_census, [marjority])

In [32]:
Orange.evaluation.CA(previsoes)

array([0.75919044])

In [33]:
for registro in base_census:
    print(registro.get_class())

<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
>50K
>50K
>50K
>50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
>50K
>50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
>50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
>50K
>50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
>50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
>50K
>50K
<=50K
<=50K
>50K
>50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
>50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
>50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
<=50K
>50K
<=

In [34]:
from collections import Counter
Counter(str(registro.get_class()) for registro in base_census)

Counter({'<=50K': 24720, '>50K': 7841})

In [35]:
import pickle
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste = pickle.load(f)

In [36]:
X_census_treinamento.shape, y_census_treinamento.shape

((27676, 108), (27676,))

In [37]:
X_census_teste.shape, y_census_teste.shape

((4885, 108), (4885,))

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
knn_census = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=2)
knn_census.fit(X_census_treinamento, y_census_treinamento)

KNeighborsClassifier(n_neighbors=10)

In [40]:
previsoes = knn_census.predict(X_census_teste)

In [41]:
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [42]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [43]:
accuracy_score(y_census_teste, previsoes)

0.8290685772773797

In [44]:
confusion_matrix(y_census_teste, previsoes)

array([[3437,  256],
       [ 579,  613]], dtype=int64)

In [45]:
classification_report(y_census_teste, previsoes)

'              precision    recall  f1-score   support\n\n       <=50K       0.86      0.93      0.89      3693\n        >50K       0.71      0.51      0.59      1192\n\n    accuracy                           0.83      4885\n   macro avg       0.78      0.72      0.74      4885\nweighted avg       0.82      0.83      0.82      4885\n'

In [46]:
import pickle
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste = pickle.load(f)

In [47]:
from sklearn.linear_model import LogisticRegression
logistic_census = LogisticRegression(random_state=1)

In [48]:
logistic_census.fit(X_census_treinamento, y_census_treinamento)

LogisticRegression(random_state=1)

In [49]:
previsoes = logistic_census.predict(X_census_teste)

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [51]:
accuracy_score(y_census_teste, previsoes)

0.849539406345957

In [52]:
confusion_matrix(y_census_teste, previsoes)

array([[3423,  270],
       [ 465,  727]], dtype=int64)

In [53]:
print(classification_report(y_census_teste, previsoes))

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      3693
        >50K       0.73      0.61      0.66      1192

    accuracy                           0.85      4885
   macro avg       0.80      0.77      0.78      4885
weighted avg       0.84      0.85      0.84      4885



In [54]:
from sklearn.svm import SVC

In [55]:
import pickle
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste = pickle.load(f)

In [56]:
svm_census = SVC(kernel='linear', random_state=1, C=2)
svm_census.fit(X_census_treinamento, y_census_treinamento)

SVC(C=2, kernel='linear', random_state=1)

In [57]:
previseos = svm_census.predict(X_census_teste)

In [58]:
accuracy_score(y_census_teste, previsoes)

0.849539406345957

In [59]:
confusion_matrix(y_census_teste, previsoes)

array([[3423,  270],
       [ 465,  727]], dtype=int64)

In [60]:
print(classification_report(y_census_teste, previsoes))

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      3693
        >50K       0.73      0.61      0.66      1192

    accuracy                           0.85      4885
   macro avg       0.80      0.77      0.78      4885
weighted avg       0.84      0.85      0.84      4885



In [61]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import NuSVC
from sklearn.neural_network import MLPClassifier