In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.naive_bayes import GaussianNB
import pickle

In [2]:
with open('census.pkl', 'rb') as f:
    (X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste) = pickle.load(f)

In [3]:
X_census_treinamento.shape, y_census_treinamento.shape

((27676, 108), (27676,))

In [4]:
X_census_teste.shape, Y_census_teste.shape

((4885, 108), (4885,))

In [5]:
naive_census = GaussianNB()
naive_census.fit(X_census_treinamento, y_census_treinamento)
previsoes = naive_census.predict(X_census_teste)
previsoes

array([' >50K', ' >50K', ' >50K', ..., ' <=50K', ' >50K', ' >50K'],
      dtype='<U6')

In [6]:
Y_census_teste

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' <=50K'],
      dtype=object)

In [7]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [8]:
accuracy_score(Y_census_teste, previsoes)

0.4767656090071648

In [9]:
confusion_matrix(Y_census_teste, previsoes)

array([[1172, 2521],
       [  35, 1157]], dtype=int64)

In [3]:
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste = pickle.load(f)

In [4]:
X_census_treinamento.shape, y_census_treinamento.shape

((27676, 108), (27676,))

In [5]:
X_census_teste.shape, Y_census_teste.shape

((4885, 108), (4885,))

In [6]:
from sklearn.tree import DecisionTreeClassifier

In [8]:
census_tree = DecisionTreeClassifier(criterion='entropy', random_state=0)
census_tree.fit(X_census_treinamento, y_census_treinamento)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [9]:
previsoes = census_tree.predict(X_census_teste)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [11]:
accuracy_score(Y_census_teste, previsoes)

0.8104401228249745

In [12]:
confusion_matrix(Y_census_teste, previsoes)

array([[3227,  466],
       [ 460,  732]], dtype=int64)

In [3]:
with open('census.pkl', 'rb') as f:
    X_census_treinamento, y_census_treinamento, X_census_teste, Y_census_teste = pickle.load(f)

In [4]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
random_forest_census = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
random_forest_census.fit(X_census_treinamento,y_census_treinamento)

RandomForestClassifier(criterion='entropy', random_state=0)

In [19]:
previsoes = random_forest_census.predict(X_census_teste)
previsoes

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [21]:
accuracy_score(Y_census_teste, previsoes)

0.8507676560900717

In [22]:
confusion_matrix(Y_census_teste, previsoes)

array([[3420,  273],
       [ 456,  736]], dtype=int64)

In [23]:
classification_report(Y_census_teste, previsoes)

'              precision    recall  f1-score   support\n\n       <=50K       0.88      0.93      0.90      3693\n        >50K       0.73      0.62      0.67      1192\n\n    accuracy                           0.85      4885\n   macro avg       0.81      0.77      0.79      4885\nweighted avg       0.85      0.85      0.85      4885\n'